### ISSUE TITLE
Not working with <a> tags

### ISSUE THREAD

**Issue by tobyzerner** [swimyoung/dom-find-and-replace#4]
Thanks for the great library!

```js
const html = findAndReplace('he<b>ll</b>o', {
  find: 'hello',
  replace: 'hi',
});
// Expected: 'hi<b></b>'
// Actual: 'hi<b></b>'
// Works!


// With an <a> tag...
const html = findAndReplace('he<a href="#">ll</a>o', {
  find: 'hello',
  replace: 'hi',
});
// Expected: 'hi<a href="#"></a>'
// Actual: 'he<a href="#">ll</a>o'
// Doesn't work :(
```

**Comment by tobyzerner** [comment]
I see this is due to https://github.com/swimyoung/dom-find-and-replace/blob/master/src/node-text.js#L64... why is `<a>` counted as a block element?

**Comment by swimyoung** [comment]
I thinks so.
Anchor link tag is not a block tag
I will delete it.

Thank you :)

**Comment by swimyoung** [comment]
Updated at [v1.2.3](https://github.com/swimyoung/dom-find-and-replace/releases/tag/v1.2.3)
Could you check it?
