### ISSUE TITLE
convert JavaScript to TypeScript

### ISSUE THREAD

**Issue by swimyoung** [swimyoung/dom-find-and-replace#8]
fascinated type system

a below image explains well
![image](https://user-images.githubusercontent.com/8675529/69237492-2a143e80-0bd9-11ea-84c4-f6e9d0e2711c.jpeg)

**Comment by ryejoon** [comment]
Awesome! Typescript + Object-oriented design for the win!

**Comment by swimyoung** [comment]
updated [v1.3.0](https://github.com/swimyoung/dom-find-and-replace/releases/tag/v1.3.0)
